import type {RunEvent} from './types';
import {Icon} from './Icon';
const labels:Record<string,string>={model:'Next step planned',risk_hint:'Outside instruction flagged',propose_tasks:'Tasks checked',preview_calendar:'Calendar preview prepared',read_document:'Document read',recommend_movies:'Taste candidates retrieved',recommend_for_group:'Group candidates ready',rank_for_group:'Group shortlist compared',refine_preferences:'Seen movies excluded',recovery:'Returned to your request',clarification:'A detail needs your review',error:'Could not finish this step'};
export function RunTimeline({events,onSource}:{events:RunEvent[];onSource?:(id:string)=>void}){
 const blocked=events.filter(e=>e.decision==='denied').length;
 return <section className="panel timeline"><div className="section-heading"><div><h2>Execution record</h2></div><Icon name="source" size={18}/></div>
 {!events.length?<div className="timeline-empty"><div className="timeline-emblem"><Icon name="shield" size={27}/></div><h3>Clear steps. No surprises.</h3><p className="empty">Verified operations appear here as the assistant works.</p><div className="process-lines"><span/><span/><span/></div></div>:<><div className="activity-summary"><span><strong>{events.filter(e=>e.decision==='allowed').length}</strong> verified steps</span>{blocked>0&&<span className="blocked-summary"><strong>{blocked}</strong> blocked</span>}</div><ol>{events.map(e=><li key={e.seq} className={e.decision==='denied'?'denied':''}><span className="timeline-symbol"><Icon name={e.decision==='denied'?'shield':e.kind==='risk_hint'?'shield':'check'} size={12}/></span><div><div className="timeline-title"><strong>{e.decision==='denied'?'Operation blocked':labels[e.tool_name||e.kind]||'Step recorded'}</strong><span className="tag">{e.decision==='denied'?'Protected':e.mode==='test'?'Test':e.decision==='allowed'?'Verified':'Recorded'}</span></div><p>{String(e.payload.message||e.payload.reason||'Recorded by the server.')}</p>{e.source&&<button className="link" onClick={()=>onSource?.(e.source!.paragraph_id)}>View source: {e.source.paragraph_id}<Icon name="arrow" size={12}/></button>}<details className="technical-detail"><summary>Technical detail</summary><code>{e.tool_name||e.kind}{e.decision?` · ${e.decision}`:''}</code></details></div></li>)}</ol></>}
 </section>;
}
